
model:
    arch: 'seresnext50_32x4d'
    input_size: 320
    num_classes: 1103
    dropout: 0

data:
    rect_crop:
        enable: true
        min_ratio: 0.3
        max_ratio: 1.0
        scale_both_dims: false

train:
    csv: '../input/train.csv'
    batch_size: 16
    folds_file: 'folds.npy'
    max_steps_per_epoch: 15000
    enable_warmup: true
    warmup:
        steps: 5000
        max_lr: 2.5e-6

test:
    csv: '../input/sample_submission.csv'
    batch_size: 32
    num_ttas: 2

optimizer:
    name: 'adam'

scheduler:
    name: 'cyclic_lr'
    params:
        max_lr: 1e-5
        base_lr: 2.5e-6
        step_size_up: 8194     # total period 3 epochs
        mode: 'triangular'
        cycle_momentum: False

loss:
    name: 'binary_cross_entropy'

augmentations:
    hflip: true
