
model:
    arch: 'seresnext50_32x4d'
    input_size: 320
    num_classes: 1103
    dropout: 0

train:
    csv: '../input/train.csv'
    batch_size: 16
    folds_file: 'folds.npy'
    max_steps_per_epoch: 15000
    enable_warmup: true
    warmup:
        steps: 5000
        max_lr: 1e-5

test:
    csv: '../input/sample_submission.csv'
    batch_size: 32
    num_ttas: 2

optimizer:
    name: 'adam'

scheduler:
    name: 'cyclic_lr'
    params:
        max_lr: 3e-4
        base_lr: 1e-5
        step_size_up: 8194     # 3 epochs
        mode: 'exp_range'
        gamma: 0.2
        cycle_momentum: False

loss:
    name: 'binary_cross_entropy'

augmentations:
    hflip: true
