
model:
    arch: 'seresnext50_32x4d'
    input_size: 320
    num_classes: 1103
    dropout: 0

train:
    csv: '../input/train.csv'
    batch_size: 8
    folds_file: 'folds.npy'
    enable_warmup: true
    use_arbitrary_sizes: true
    warmup:
        steps: 5000
        max_lr: 1e-4
    mixup:
        enable: true
        beta_a: 0.3

test:
    csv: '../input/sample_submission.csv'
    batch_size: 8
    num_ttas: 2

optimizer:
    name: 'adam'
    params:
        lr: 1e-4

scheduler:
    name: 'reduce_lr_on_plateau'
    params:
        factor: 0.2
        patience: 2
        min_lr: 3e-7
        threshold: 1e-3

loss:
    name: 'binary_cross_entropy'

augmentations:
    hflip: true
    erase:
        prob: 0.5
        min_area: 0.02
        max_area: 0.4
        min_ratio: 0.3
        max_ratio: 3.33
