
model:
    arch: 'pnasnet5large'
    input_size: 352
    num_classes: 1103
    dropout: 0.5

data:
    rect_crop:
        enable: true
        min_ratio: 0.5
        max_ratio: 1.0
        scale_both_dims: false

train:
    csv: 'train.csv'
    batch_size: 6
    folds_file: 'folds.npy'
    max_steps_per_epoch: 10600
    enable_warmup: true
    num_epochs: 1000
    warmup:
        steps: 5000
        max_lr: 1e-4
    mixup:
        enable: true
        beta_a: 0.3

test:
    csv: 'sample_submission.csv'
    batch_size: 32
    num_ttas: 2

optimizer:
    name: 'adam'
    params:
        lr: 1e-4

scheduler:
    name: 'reduce_lr_on_plateau'
    params:
        factor: 0.2
        patience: 2
        min_lr: 3e-7
        threshold: 1e-3

cosine:
    start_lr: 3e-5
    period: 3
    period_inc: 1
    max_period: 5

loss:
    name: 'binary_cross_entropy'

augmentations:
    # affine: 'medium'
    hflip: true
    blur: 0.3
    distortion: 0.2
    noise: 0.3
    erase:
        prob: 0.5
        min_area: 0.02
        max_area: 0.4
        min_ratio: 0.3
        max_ratio: 3.33
